from discordctl.ops.registry import REGISTRY, load_all_handlers

EXPECTED_MUTATING = {
    "guild.edit",
    "guild.apply",
    "channel.create",
    "channel.edit",
    "channel.delete",
    "channel.move",
    "channel.clone",
    "channel.sync",
    "category.create",
    "category.edit",
    "category.delete",
    "category.move",
    "role.create",
    "role.edit",
    "role.delete",
    "role.move",
    "role.clone",
    "role.permissions_set",
    "member.ban",
    "member.unban",
    "member.kick",
    "member.timeout",
    "member.untimeout",
    "member.nick",
    "member.roles_add",
    "member.roles_remove",
    "member.roles_set",
    "member.voice_move",
    "member.voice_disconnect",
    "member.self_edit",
    "bot.presence_set",
    "bot.presence_clear",
    "bot.profile_edit",
    "bot.leave_guild",
    "message.send",
    "message.edit",
    "user.dm_send",
    "poll.end",
    "message.delete",
    "message.purge",
    "message.pin",
    "message.unpin",
    "message.react",
    "message.reaction_remove",
    "message.reactions_clear",
    "message.crosspost",
    "message.bulk_delete",
    "permissions.channel_overwrite_set",
    "permissions.channel_overwrite_clear",
    "thread.create_forum_post",
    "thread.create",
    "thread.create_from_message",
    "thread.edit",
    "thread.archive",
    "thread.lock",
    "thread.join",
    "thread.leave",
    "thread.member_add",
    "thread.member_remove",
    "thread.delete",
    "event.create",
    "event.edit",
    "event.delete",
    "automod.create",
    "automod.edit",
    "automod.delete",
    "emoji.create",
    "emoji.delete",
    "sticker.create",
    "sticker.edit",
    "sticker.delete",
    "stage.create",
    "stage.edit",
    "stage.delete",
    "invite.create",
    "invite.delete",
    "webhook.create",
    "webhook.delete",
    "webhook.edit",
    "webhook.execute",
    "webhook.message_edit",
    "webhook.message_delete",
    "guild.prune",
    "guild.onboarding_edit",
    "guild.welcome_screen_edit",
    "guild.widget_edit",
    "guild.integration_delete",
    "guild.incident_actions_set",
    "member.bulk_ban",
    "template.create",
    "template.sync",
    "template.edit",
    "template.delete",
}

EXPECTED_READ = {
    "bot.ping",
    "bot.version",
    "bot.guilds",
    "bot.stats",
    "bot.presence_get",
    "bot.gateway",
    "user.me",
    "user.get",
    "guild.info",
    "guild.snapshot",
    "guild.diff",
    "guild.audit_log",
    "channel.list",
    "channel.info",
    "category.list",
    "category.info",
    "category.children",
    "role.list",
    "role.info",
    "member.list",
    "member.search",
    "member.info",
    "message.history",
    "message.search",
    "message.get",
    "message.reactions_list",
    "message.pins_list",
    "poll.voters",
    "permissions.channel_overwrites",
    "permissions.resolve_member",
    "permissions.resolve_role",
    "thread.list_active",
    "thread.list_archived",
    "thread.info",
    "thread.history",
    "thread.member_info",
    "thread.members_list",
    "event.list",
    "event.info",
    "event.users",
    "automod.list",
    "automod.info",
    "emoji.list",
    "sticker.list",
    "sticker.info",
    "sticker.get",
    "sticker.packs",
    "stage.info",
    "invite.list",
    "webhook.list",
    "webhook.info",
    "webhook.guild_list",
    "webhook.message_get",
    "guild.prune_count",
    "guild.onboarding_get",
    "guild.welcome_screen_get",
    "guild.widget_get",
    "guild.integrations_list",
    "guild.preview",
    "guild.voice_regions",
    "guild.vanity_url",
    "member.bans_list",
    "member.ban_info",
    "role.member_counts",
    "template.list",
    "template.get",
}


def test_all_handlers_load():
    load_all_handlers()
    assert len(REGISTRY.ops()) == 159


def test_mutating_flags_match_plan():
    load_all_handlers()
    assert REGISTRY.mutating_ops() == EXPECTED_MUTATING


def test_read_ops_match_plan():
    load_all_handlers()
    read_ops = set(REGISTRY.ops()) - REGISTRY.mutating_ops()
    assert read_ops == EXPECTED_READ


def test_op_set_is_exactly_catalog():
    load_all_handlers()
    assert set(REGISTRY.ops()) == EXPECTED_MUTATING | EXPECTED_READ
